(() => {
  const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&#38;','<':'&#60;','>':'&#62;','"':'&#34;',"'":'&#39;'}[m]));
  let stations=[],fuel='g95',radius=10,current=null,loadToken=0,viewportTimer=null,nationalLoading=false;
  const SPAIN_CENTER=[40.2,-3.7];
  function openMap(){ $('home').classList.add('hidden');$('app').classList.remove('hidden');GasolinaGoMap.init();GasolinaGoMap.invalidate(); }
  function setStatus(html){$('stationList').innerHTML=html}
  async function request(url,token){const r=await fetch(url,{cache:'no-store'}),data=await r.json();if(token!==loadToken)return null;if(!r.ok)throw new Error(data.error||'No se pudieron cargar los precios');return data}
  async function loadNationalViewport(){if(!current?.explore||nationalLoading)return;clearTimeout(viewportTimer);viewportTimer=setTimeout(async()=>{const b=GasolinaGoMap.getBounds();if(!b)return;const token=++loadToken;nationalLoading=true;try{const qs=new URLSearchParams({explore:'1',south:b.south.toFixed(4),west:b.west.toFixed(4),north:b.north.toFixed(4),east:b.east.toFixed(4)}),data=await request('/api/precios?'+qs.toString(),token);if(!data)return;stations=Array.isArray(data.estaciones)?data.estaciones:[];render();if(!stations.length)setStatus('<div class="station-meta" style="padding:10px">No hay gasolineras en esta zona del mapa.</div>')}catch(e){if(token===loadToken)setStatus('<div class="station-meta" style="padding:10px;color:var(--red)">'+esc(e.message||'No se pudieron cargar las gasolineras.')+'</div>')}finally{nationalLoading=false}},250)}
  async function loadArea(lat,lng,label,province,explore=false){const token=++loadToken;$('homeError').textContent='';openMap();$('place').textContent=label||'Cerca de ti';$('detail').classList.remove('open');current={lat,lng,label,province,explore};if(explore){GasolinaGoMap.fitSpain();setStatus('<div class="station-meta" style="padding:10px">Cargando gasolineras de la zona visible…</div>');setTimeout(loadNationalViewport,150);return}setStatus('<div class="station-meta" style="padding:10px">Buscando gasolineras…</div>');GasolinaGoMap.setView(lat,lng,12);try{const qs=new URLSearchParams({lat:String(lat),lng:String(lng),radio:String(radius)});if(province)qs.set('provincia',province);const data=await request('/api/precios?'+qs.toString(),token);if(!data)return;stations=Array.isArray(data.estaciones)?data.estaciones:[];render();const valid=stations.filter(s=>Number.isFinite(Number(s.lat))&&Number.isFinite(Number(s.lng)));if(valid.length)GasolinaGoMap.fitBounds(valid.map(s=>[s.lat,s.lng]),{maxZoom:13});if(!stations.length)setStatus('<div class="station-meta" style="padding:10px">No hay gasolineras disponibles en esta zona.</div>')}catch(e){if(token===loadToken)setStatus('<div class="station-meta" style="padding:10px;color:var(--red)">'+esc(e.message||'No se pudieron cargar las gasolineras.')+'</div>')}}
  function render(){GasolinaGoMap.clear();const valid=GasolinaGoStations.render(stations,fuel,s=>selectStation(s));valid.forEach(s=>{const marker=GasolinaGoMap.markerFor(s,fuel,selectStation);if(marker)GasolinaGoMap.addMarker(marker)})}
  function selectStation(s){GasolinaGoMap.setView(Number(s.lat),Number(s.lng),16);GasolinaGoStations.showDetail(s)}
  function selectSuggestion(i){const x=GasolinaGoSearch.getResults()[i];if(!x)return;$('searchInput').value=x.nombre;GasolinaGoSearch.hide();loadArea(Number(x.lat),Number(x.lng),x.nombre+' · '+x.provincia,x.provincia,false)}
  function useLocation(){if(!navigator.geolocation){$('homeError').textContent='Tu navegador no permite obtener la ubicación.';return}$('homeError').textContent='Obteniendo tu ubicación…';navigator.geolocation.getCurrentPosition(p=>loadArea(p.coords.latitude,p.coords.longitude,'Cerca de ti','',false),()=>{$('homeError').textContent='No hemos podido obtener tu ubicación. Puedes buscar una ciudad.'},{enableHighAccuracy:false,timeout:10000,maximumAge:300000})}
  function changeRadius(value){radius=Number(value);document.querySelectorAll('.radius').forEach(b=>b.classList.toggle('on',Number(b.dataset.radius)===radius));if(current&&!current.explore)loadArea(current.lat,current.lng,current.label,current.province,false)}
  function init(){GasolinaGoSearch.init(selectSuggestion);$('useLocation').addEventListener('click',useLocation);$('explore').addEventListener('click',()=>loadArea(SPAIN_CENTER[0],SPAIN_CENTER[1],'España','',true));$('back').addEventListener('click',()=>{$('app').classList.add('hidden');$('home').classList.remove('hidden');GasolinaGoMap.destroy();current=null;stations=[];loadToken++;});$('closeDetail').addEventListener('click',()=>$('detail').classList.remove('open'));$('myLocation').addEventListener('click',useLocation);document.querySelectorAll('.fuel').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.fuel').forEach(x=>x.classList.remove('on'));b.classList.add('on');fuel=b.dataset.fuel;render()}));document.querySelectorAll('.radius').forEach(b=>b.addEventListener('click',()=>changeRadius(b.dataset.radius)));GasolinaGoMap.onMove(()=>{if(current?.explore&&GasolinaGoMap.getZoom()>=6)loadNationalViewport()})}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();window.GasolinaGoApp={loadArea};
})();